name: 'Terraform Deploy'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/terraform-destroy.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/terraform-destroy.yaml'

permissions:
  contents: read

jobs:
  terraform_root:
    name: 'Terraform AWS Infra'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ vars.AWS_REGION }}
      TF_VAR_availability_zones: ${{ vars.AVAILABILITY_ZONES }}
      TF_VAR_bucket_name: ${{ vars.BUCKET_NAME }}
      TF_VAR_cluster_name: ${{ vars.CLUSTER_NAME }}
      TF_VAR_vpc_name: ${{ vars.VPC_NAME }}
      TF_VAR_igw_name: ${{ vars.IGW_NAME }}
      TF_VAR_public_route_table_name: ${{ vars.PUBLIC_ROUTE_TABLE_NAME }}
      TF_VAR_public_subnet_name_prefix: ${{ vars.PUBLIC_SUBNET_NAME_PREFIX }}
      TF_VAR_ng_general_ondemand: ${{ vars.NG_GENERAL_ONDEMAND }}
      TF_VAR_general_ondemand_instance_types: ${{ vars.GENERAL_ONDEMAND_INSTANCE_TYPES }}
      TF_VAR_private_cidr_blocks: ${{ vars.PRIVATE_CIDR_BLOCKS }}
      TF_VAR_public_cidr_blocks: ${{ vars.PUBLIC_CIDR_BLOCKS }}
      TF_VAR_vpc_cidr: ${{ vars.VPC_CIDR }}
      TF_VAR_registry_org: ${{ vars.GIT_ORG }}
      TF_VAR_infra_repo_name: ${{ vars.INFRA_REPO_NAME}}
      TF_VAR_general_ondemand_max_nodes: ${{vars.GENERAL_ONDEMAND_MAX_NODES}}
      TF_VAR_general_ondemand_desired_nodes: ${{vars.GENERAL_ONDEMAND_DESIRED_NODES}}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    # Sets up Terraform CLI on the GitHub Actions runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Terraform Init, Plan, and Apply for the root directory
    - name: Prepare Main Terraform Configuration -- Root
      run: |
        envsubst < ./main.tf.tpl > ./main.tf
      working-directory: ./infra

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init - Root
      run: terraform init
      working-directory: ./infra

    # Validates the Terraform configuration files to ensure they are syntactically valid and internally consistent
    # This step helps catch configuration errors before applying the plan
    - name: Terraform Validate - Root
      run: terraform validate
      working-directory: ./infra

    # Generates an execution plan for Terraform
    - name: Terraform Plan - Root
      run: terraform plan -input=false -refresh=true -out=tfplan.out
      working-directory: ./infra

    # Shows the details of the execution plan for Terraform
    - name: Terraform Show - Root
      run: terraform show tfplan.out
      working-directory: ./terraform_autoscalar

    # Applies the Terraform plan to create or update infrastructure
    # -auto-approve: Automatically approves any changes to avoid manual confirmation
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false tfplan.out
      working-directory: ./infra
